---
- name: Install Python 2 if not installed
  raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
  when: ansible_os_family == 'Debian'

- name: Upgrade system packages on Debian
  apt:
    upgrade: dist
    update_cache: yes
  when: ansible_os_family == 'Debian'

- name: Add wireguard repository
  apt_repository:
    repo: deb https://deb.debian.org/debian unstable main
    state: present
    filename: unstable-wireguard.list
    update_cache: true
  when: ansible_os_distribution == 'Debian'

- name: Install wireguard
  package:
    name: "{{item}}"
    state: latest
  with_items:
    - wireguard-dkms
    - wireguard-tools

## Configure system environment
- name: Enable packet forwarding for IPv4
  sysctl:
    name: net.ipv4.ip_forward
